# Generated by Django 3.1.4 on 2021-01-12 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.TextField(blank=True, max_length=500)),
                ('address2', models.TextField(blank=True, max_length=500)),
                ('phonenumber', models.IntegerField(blank=True, null=True)),
                ('pincode', models.CharField(blank=True, max_length=200)),
                ('addeddate', models.DateTimeField(auto_now=True)),
                ('enddate', models.DateTimeField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
