# Generated by Django 3.1.4 on 2021-01-16 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20210112_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='tax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productImage', models.ImageField(blank=True, null=True, upload_to='productimages/')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.products')),
            ],
        ),
    ]
