# Generated by Django 3.1.4 on 2021-01-20 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0005_auto_20210116_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=50)),
                ('grandtotal', models.IntegerField()),
                ('orderdate', models.DateTimeField(auto_now=True)),
                ('enddate', models.DateTimeField(null=True)),
                ('billeddate', models.DateTimeField(null=True)),
                ('status', models.IntegerField()),
                ('isfulfilled', models.IntegerField()),
                ('isdeleted', models.IntegerField()),
                ('paymentmode', models.IntegerField()),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('producttotal', models.IntegerField()),
                ('addeddate', models.DateTimeField(auto_now=True)),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.order')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.products')),
            ],
        ),
    ]
