# Generated by Django 3.1.4 on 2021-01-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_order_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveredaddress',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='orderaccepteddate',
            field=models.DateTimeField(null=True),
        ),
    ]
