# Generated by Django 3.1.4 on 2021-01-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20210122_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
