# Generated by Django 3.1.4 on 2021-01-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20210123_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='isdeleted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='isfulfilled',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentmode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
