# Generated by Django 3.1.4 on 2021-02-03 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20210123_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('addeddate', models.DateTimeField(auto_now=True)),
                ('enddate', models.DateTimeField(null=True)),
                ('status', models.IntegerField()),
                ('parentcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.category')),
            ],
        ),
    ]
