# Generated by Django 3.1.4 on 2021-02-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='subcategoryid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
