# Generated by Django 3.1.4 on 2021-02-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_auto_20210213_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannertag', models.CharField(max_length=5)),
                ('bannerimage', models.ImageField(blank=True, null=True, upload_to='banners/')),
            ],
        ),
    ]
