# Generated by Django 3.1.4 on 2021-02-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_auto_20210215_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='companylogo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='companytag',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
