# Generated by Django 3.1.4 on 2021-03-17 15:56

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_auto_20210215_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='deliverydetails',
            field=models.TextField(blank=True, max_length=builtins.max),
        ),
        migrations.AddField(
            model_name='products',
            name='features',
            field=models.TextField(blank=True, max_length=builtins.max),
        ),
    ]
