# Generated by Django 3.1.4 on 2021-05-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_auto_20210327_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zipcodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=50)),
                ('addeddate', models.DateTimeField()),
                ('enddate', models.DateTimeField(null=True)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='address1',
            new_name='housename',
        ),
        migrations.AddField(
            model_name='profile',
            name='landmark',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
